### ISSUE TITLE
lspeig has suspicious code

### ISSUE THREAD

**Issue by schwehr** [dwcaress/MB-System#1023]
I don't think this is what was intended.

- icyc never incremented or used inside the loop
- i incr'ed, but never tested or used

https://github.com/dwcaress/MB-System/blob/master/src/mbaux/mb_cheb.c#L459

```c
	for (icyc = 0; icyc < 25 && res > eps; i++) {
		smp = 0.5 * (*sup + slo);
		errsmp = errrat(*smax, smp, sigma, *nsig);
		if (errsmp > eps)
			slo = smp;
		else
			*sup = smp;
		res = (*sup - slo) / slo;
	}
```

**Comment by dwcaress** [comment]
Agreed. I went back to Allen Olsen's original fortran, and the i++ should be icyc++.  I guess this loop has been exiting on convergence only for 20 years.

**Comment by dwcaress** [comment]
Fixed in mb_cheb.c

**Comment by schwehr** [comment]
Dave, next tune, put "Fixes #1023" in your commit.  Then the commit will automatically closes the bug and leaves a link in the bug.  This creates a narrative making that builds builds a knowledge base overtime that makes it easier for all to understand the project.

Can you share the link to the original code?

**Comment by schwehr** [comment]
Fixed in https://github.com/dwcaress/MB-System/commit/7b0d02f4456740a69da3794833253346fa861171

**Comment by dwcaress** [comment]
Kurt,
Linking to something implies putting it somewhere. I found cheb.f in a backup of the RAID array we used circa 2000. You also asked about linking to the original HMRG code, which I only have as email attachments. Should original source codes be part of the MB-System repository?

**Comment by schwehr** [comment]
You can put it in a GitHub gist

**Comment by dwcaress** [comment]
The original Fortran source code is available at:
https://gist.github.com/dwcaress/141d0df01d4f564618cab402c553aa54
