### ISSUE TITLE
mbedit || should maybe be &&

### ISSUE THREAD

**Issue by schwehr** [dwcaress/MB-System#1041]
```
mbedit_prog.c:3351:35: style: Condition 'filter_cutbeam_begin>filter_cutbeam_end' is always true [knownConditionTrueFalse]
    else if (filter_cutbeam_begin > filter_cutbeam_end) {
                                  ^
mbedit_prog.c:3405:39: style: Condition 'filter_cutdistance_begin>filter_cutdistance_end' is always true [knownConditionTrueFalse]
    else if (filter_cutdistance_begin > filter_cutdistance_end) {
                                      ^
mbedit_prog.c:3462:36: style: Condition 'filter_cutangle_begin>filter_cutangle_end' is always true [knownConditionTrueFalse]
    else if (filter_cutangle_begin > filter_cutangle_end) {
```

**Comment by dwcaress** [comment]
Addressed by commit #1069.
Addressed TODO's left by Kurt in mbedit_prog.c in conjunction with issue #1041. The always true else statements have been commented out. Some variables converted to bool as suggested.  The logic questioned for the reverse cut filters is correct and has been left in place. When begin < end then the cut is in the interior of the swath. When begin > end then cuts are made at the outer edges of the swath.
