### ISSUE TITLE
Update link to GMT

### ISSUE THREAD

**Issue by PaulWessel** [dwcaress/MB-System#1054]
Perhaps pages like [this one](https://www.mbari.org/products/research-software/mb-system/how-to-download-and-install-mb-system/#toggle-id-4) as well as general documentation could update the URL to the GMT site.  Since last fall we are www.generic-mapping-tools.org.  The old link to gmt.soest.hawaii.edu goes to the deprecated wiki which will eventually be removed.

**Comment by dwcaress** [comment]
Paul,

Fixed (I think).

Thanks,
Dave


> On Apr 10, 2020, at 10:24 PM, Paul Wessel <notifications@github.com> wrote:
> 
> 
> Perhaps pages like this one as well as general documentation could update the URL to the GMT site. Since last fall we are www.generic-mapping-tools.org. The old link to gmt.soest.hawaii.edu goes to the deprecated wiki which will eventually be removed.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

----------------------------------------------------
David W. Caress
Principal Engineer
Seafloor Mapping Lab

Monterey Bay Aquarium Research Institute
7700 Sandholdt Road
Moss Landing, CA 95039

caress@mbari.org
http://www.mbari.org/~caress/

Phone: 831-775-1775
