### ISSUE TITLE
No longer possible to checkout from Windows

### ISSUE THREAD

**Issue by joa-quim** [dwcaress/MB-System#1072]
Names starting with colons are not possible on Windows so the checkout errors at

https://github.com/dwcaress/MB-System/tree/master/src/qttest/:Users:caress:sandbox:MB-System:src:qttest:build-mbgrdviz-2-Desktop_Qt_5_14_2_clang_64bit-Debug/mbgrdviz-2.app/Contents

**Comment by dwcaress** [comment]
Removed with commit #1073
