### ISSUE TITLE
Compile error when building 5.7.6beta34

### ISSUE THREAD

**Issue by anbj** [dwcaress/MB-System#1090]
Doing `make` for the new 5.7.6beta34, I get the following:

```
In file included from /usr/local/include/gmt/gmt_dev.h:169,
                 from mbgrd2obj.c:53:
/usr/local/include/gmt/gmt_prototypes.h:81:30: note: expected ‘struct GMT_OPTION **’ but argument is of type ‘struct GMT_CTRL **’
   81 | EXTERN_MSC struct GMT_CTRL * gmt_init_module (struct GMTAPI_CTRL *API, const char *lib_name, const char *mod_name, const char *keys, const char *required, struct GMT_KEYWORD_DICTIONARY *this_module_kw, struct GMT_OPTION **options, struct GMT_CTRL **Ccopy);
      |                              ^~~~~~~~~~~~~~~
mbgrd2obj.c:238:13: error: too few arguments to function ‘gmt_init_module’
  238 |  if ((GMT = gmt_init_module (API, THIS_MODULE_LIB, THIS_MODULE_CLASSIC_NAME, THIS_MODULE_KEYS, THIS_MODULE_NEEDS, &options, &GMT_cpy)) == NULL) bailout (API->error); /* Save current state */
      |             ^~~~~~~~~~~~~~~
```

Note the `mbgrd2obj.c:238:13: error: too few arguments to function ‘gmt_init_module’` 

Compiled GMT is git head (master).

**Comment by dwcaress** [comment]
Ok, thanks. I tested relative to GMT 6.0.0 but not the current master. Some more #ifdefs are likely required.

Cheers,
Dave

> On May 14, 2020, at 2:11 AM, anbj <notifications@github.com> wrote:
> 
> 
> Doing make for the new 5.7.6beta34, I get the following:
> 
> In file included from /usr/local/include/gmt/gmt_dev.h:169,
>                  from mbgrd2obj.c:53:
> /usr/local/include/gmt/gmt_prototypes.h:81:30: note: expected ‘struct GMT_OPTION **’ but argument is of type ‘struct GMT_CTRL **’
>    81 | EXTERN_MSC struct GMT_CTRL * gmt_init_module (struct GMTAPI_CTRL *API, const char *lib_name, const char *mod_name, const char *keys, const char *required, struct GMT_KEYWORD_DICTIONARY *this_module_kw, struct GMT_OPTION **options, struct GMT_CTRL **Ccopy);
>       |                              ^~~~~~~~~~~~~~~
> mbgrd2obj.c:238:13: error: too few arguments to function ‘gmt_init_module’
>   238 |  if ((GMT = gmt_init_module (API, THIS_MODULE_LIB, THIS_MODULE_CLASSIC_NAME, THIS_MODULE_KEYS, THIS_MODULE_NEEDS, &options, &GMT_cpy)) == NULL) bailout (API->error); /* Save current state */
>       |             ^~~~~~~~~~~~~~~
> 
> Compiled GMT is git head (master).
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

----------------------------------------------------
David W. Caress
Principal Engineer
Seafloor Mapping Lab

Monterey Bay Aquarium Research Institute
7700 Sandholdt Road
Moss Landing, CA 95039

caress@mbari.org
http://www.mbari.org/~caress/

Phone: 831-775-1775

**Comment by anbj** [comment]
The latest master compiles without problems.

However, I'm on Ubuntu Focal Fossa 20.04, and doing ``./configure``, ``make`` and ``sudo make install`` and then testing with ``mbdatalist`` gives:

```
$ mbdatalist -v
mbdatalist: error while loading shared libraries: libmbio.so.0: cannot open shared object file: No such file or directory
```
with ``find``:
```
$ find / -name "libmbio.so.0"
/usr/local/lib/libmbio.so.0
```

Doing a `ln -s /usr/local/lib/libmbio.so.0 /usr/lib/libmbio.so.0` fixes the problem. This needs to be done with all these type of files I guess. Is this Ubuntu-related or MB-System-related?

**Comment by dwcaress** [comment]
The following is from 
   https://www.mbari.org/products/research-software/mb-system/how-to-download-and-install-mb-system/#toggle-id-9 

As with most of the documentation this is a bit out of date.  In particular, one should avoid using the LD_LIBRARY_PATH environment variable for security and robustness, and so the option of adding the CFLAGS preset to the configure command is preferred:

>
> In some cases the system and/or user environment impedes the successful 
> use of the GMT and/or MB-System shared libraries. In order to manually allow 
> shared libraries to be found for linking or running, one can either set the CFLAGS 
> environment variable during building or set the LD_LIBRARY_PATH environment 
> variable at login by adding a command to the user’s ~/.profile or ~/.bashrc files.
> 
> To set the CFLAGS environment variable during building include “-Wl,-rpath -Wl,LIBDIR” in the configure command as shown here:
> 
> sudo CFLAGS="-Wl,-rpath -Wl,/usr/local/lib" ./configure
> 
> To augment the LD_LIBRARY_PATH environment variable during login add a line to the ~/.bashrc or ~/.profile file as shown here:
> 
> export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
>

**Comment by anbj** [comment]
Great, Dave. Thanks for the tip!
