### ISSUE TITLE
OSRExportToProj4 should not allocate a GMT variable and let GMT free it. That's a Boom on Windows.

### ISSUE THREAD

**Issue by joa-quim** [dwcaress/MB-System#1094]
I'm getting  crash with mbgrid at the end when it calls GMT to free ``header->ProjRefPROJ4``. Surprisingly this only occurs with GMT debug builds. I say surprisingly because it should happen also with normal builds. The issue, I think, is that in ``mb_readwritegrd()``

```
    if ((eErr = OSRExportToProj4(hSRS, &header->ProjRefPROJ4)) != OGRERR_NONE) {
      fprintf(stderr, "Failed to convert the SRS to Proj syntax\n");
    }
    OSRDestroySpatialReference(hSRS);
  }
  fprintf(stderr,"header->ProjRefPROJ4:%s\n", header->ProjRefPROJ4);
```
but that allocates the pointer ``header->ProjRefPROJ4`` in GDAL but that pointer is then freed in GMT. On Windows this is a no-no. One cannot cross-dlls like that. Memory allocated in one dll must be freed in it.

On GMT we deal with that case using a temporary variable, like
```
		if (OSRImportFromWkt(hSRS, &pszProjection) == CE_None) {
			OSRExportToProj4(hSRS, &pszResult);
			Ctrl->ProjRefPROJ4 = strdup(pszResult);
			CPLFree(pszResult);
		}
```

also, there is no need to 
```
fprintf(stderr,"header->ProjRefPROJ4:%s\n", header->ProjRefPROJ4);
```

**Comment by dwcaress** [comment]
Thanks. I tried to fix this with #1095.

**Comment by joa-quim** [comment]
Sorry, should have thought on that. It's still no good because the same problem remains. Now it's allocated in MB and freed in GMT. But we happen to have a function that saves the situation. Please use

```
header->ProjRefPROJ4 = gmt_strdup_noquote(pszResult);
```
Sorry for not submitting PRs but I have a very old fork.

**Comment by dwcaress** [comment]
Try again with #1096.
