### ISSUE TITLE
Problem compiling Pre-release 5.7.6beta38 

### ISSUE THREAD

**Issue by anbj** [dwcaress/MB-System#1104]
I'm trying to compile Pre-release 5.7.6beta38 and getting into some trouble. I'm using bleeding edge GMT.

```
[...]
In file included from mb_readwritegrd.c:29:
/usr/local/include/gmt/gmt_dev.h:164:10: fatal error: gmt_remote.h: No such file or directory
  164 | #include "gmt_remote.h"          /* GMT type declarations */
      |          ^~~~~~~~~~~~~~
[...]
```

**Comment by dwcaress** [comment]
It looks like a new header file gmt_remote.h was added to GMT a few days ago and is now referenced in gmt_dev.h. However, the build system is not installing gmt_remote.h with the other GMT header files. I have submitted an issue to the GMT github repository ( GenericMappingTools/gmt/#3449 ).

**Comment by dwcaress** [comment]
Paul Wessel fixed the problem with GMT. I just downloaded the current GMT master, built and installed it, and was then able to build and install MB-System 5.7.6beta38.

**Comment by anbj** [comment]
Built and installed. Thanks Dave!
