### ISSUE TITLE
MB System installation on Mac OS  Big Sur

### ISSUE THREAD

**Issue by ndahlan** [dwcaress/MB-System#1174]
I am trying to install the software MB system on my Mac with the latest os Big Sur but having some problem with the error message as shown below:

——
Last 15 lines from /Users/nurdin/Library/Logs/Homebrew/mbsystem/02.make:
make[2]: *** [libmbview_la-mbview_site.lo] Error 1
1 error generated.
1 error generated.
mv -f .deps/libmbview_la-MB3DNavList.Tpo .deps/libmbview_la-MB3DNavList.Plo
make[2]: *** [libmbview_la-mbview_pick.lo] Error 1
make[2]: *** [libmbview_la-mbview_plot.lo] Error 1
mv -f .deps/libmbview_la-MB3DRouteList.Tpo .deps/libmbview_la-MB3DRouteList.Plo
1 error generated.
mv -f .deps/libmbview_la-MB3DSiteList.Tpo .deps/libmbview_la-MB3DSiteList.Plo
make[2]: *** [libmbview_la-mbview_process.lo] Error 1
1 error generated.
make[2]: *** [libmbview_la-mbview_callbacks.lo] Error 1
mv -f .deps/libmbview_la-MB3DView.Tpo .deps/libmbview_la-MB3DView.Plo
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
———

MacOS Big Sur
Version 11.1

**Comment by dwcaress** [comment]
Nurdin,

Questions like this are best asked using the user discussion list at:
	https://www.mbari.org/products/research-software/mb-system/mb-system-discussion-lists/

I have edited the README.md at the top of the code repository to make this more clear.

What you show below is insufficient for me to understand your problem.

However, I am able to install MB-System on a MacBook Pro running Big Sur with the current Xcode either through Homebrew or by building locally with the prerequisites installed using Homebrew. Directions for this are found on the main website at:
	https://www.mbari.org/products/research-software/mb-system/how-to-download-and-install-mb-system/

I hope this helps.

Dave

**Comment by dwcaress** [comment]
Nurdin,

Questions like this are best asked using the user discussion list at:
	https://www.mbari.org/products/research-software/mb-system/mb-system-discussion-lists/

I have edited the README.md at the top of the code repository to make this more clear.

What you show below is insufficient for me to understand your problem.

However, I am able to install MB-System on a MacBook Pro running Big Sur with the current Xcode either through Homebrew or by building locally with the prerequisites installed using Homebrew. Directions for this are found on the main website at:
	https://www.mbari.org/products/research-software/mb-system/how-to-download-and-install-mb-system/

I hope this helps.

Dave


> On Dec 28, 2020, at 5:48 AM, Nurdin Dahlan <notifications@github.com> wrote:
> 
> 
> I am trying to install the software MB system on my Mac with the latest os Big Sur but having some problem with the error message as shown below:
> 
> ——
> Last 15 lines from /Users/nurdin/Library/Logs/Homebrew/mbsystem/02.make:
> make[2]: *** [libmbview_la-mbview_site.lo] Error 1
> 1 error generated.
> 1 error generated.
> mv -f .deps/libmbview_la-MB3DNavList.Tpo .deps/libmbview_la-MB3DNavList.Plo
> make[2]: *** [libmbview_la-mbview_pick.lo] Error 1
> make[2]: *** [libmbview_la-mbview_plot.lo] Error 1
> mv -f .deps/libmbview_la-MB3DRouteList.Tpo .deps/libmbview_la-MB3DRouteList.Plo
> 1 error generated.
> mv -f .deps/libmbview_la-MB3DSiteList.Tpo .deps/libmbview_la-MB3DSiteList.Plo
> make[2]: *** [libmbview_la-mbview_process.lo] Error 1
> 1 error generated.
> make[2]: *** [libmbview_la-mbview_callbacks.lo] Error 1
> mv -f .deps/libmbview_la-MB3DView.Tpo .deps/libmbview_la-MB3DView.Plo
> make[1]: *** [install-recursive] Error 1
> make: *** [install-recursive] Error 1
> ———
> 
> MacOS Big Sur
> Version 11.1
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

----------------------------------------------------
David W. Caress
Principal Engineer
Seafloor Mapping Lab

Monterey Bay Aquarium Research Institute
7700 Sandholdt Road
Moss Landing, CA 95039

caress@mbari.org
http://www.mbari.org/~caress/

Phone: 831-775-1775

**Comment by ndahlan** [comment]
Hi David,

Thank you so much for your email.  I have managed to install the software
but still have an issue with the XQuartz. I will post the question the in
the discussion page as you suggested.

Thanks again for your help.

Best regards,
Nurdin
