### ISSUE TITLE
configure and build mb-stystem on headless server with no X dependencies

### ISSUE THREAD

**Issue by epifanio** [dwcaress/MB-System#1195]
**Is your feature request related to a problem? Please describe.**
I am trying to build MB-System on a remote server. Is it possible to configure MB-System without the need to install dependencies related to its user interface?  

This will help in keeping a low footprint on the system, but also helping out with the build, At the moment I am building in a conda environment and the configure script is failing on:

```
Check for X11 libraries libX11 libXt and X11 header file X11/Intrinsic.h
checking for XtAppMainLoop in -lXt... yes
checking for XSendEvent in -lX11... yes
checking X11/Intrinsic.h usability... yes
checking X11/Intrinsic.h presence... yes
checking for X11/Intrinsic.h... yes
Found X11 libraries libX11 libXt and X11 header file X11/Intrinsic.h
Check for Motif library libXm
Motif library location specified: /modules/centos7/user-apps/fou-fd/miniconda-mds/envs/rapids-0.19/lib/ - check if libXm is there...
checking for XmCreatePushButton in -lXm... no
configure: error: Did not find libXm according to --with-motif-lib - check the installation!
```

**Describe the solution you'd like**
Make the dependency on `libopenmotiff` or `lesstiff` and other X-related libraries, optional. so that will be still possible to build mbsystem command-line utilities.

**Comment by dwcaress** [comment]
I think that this option exists. If you run the configure script with the option --disable-mbtools it will construct the makefiles such that all the graphical tools are skipped. I tested this on my Mac running Catalina using 
./configure \
    --prefix=/usr/local \
    --with-otps-dir=/usr/local/opt/otps \
    --enable-hardening \
    --enable-test \
    --disable-mbtools

and I was able to build and install the nongraphical applications successfully.

**Comment by epifanio** [comment]
Hi @dwcaress , thanks for your reply -  disabling  mbtools with `--disable-mbtools`,  is working on git master but I can't get it to work on v5.7 release - this is the configure output: 

https://gist.github.com/epifanio/06a16d92ab2c2666493a0d001d84ea6d 

 I am using 5.7 because was the last MB-System version ( that I've tried) which gave me a working PDAL-MB-Ststem driver.
 Building PDAL against the latest MB-System (git master) didn't work, the PDAL readers.mbio driver gets built but is not loading.  So I am forced to use v5.7. 
 Do you have any hints on what could I modify in the v5.7 configure scripts to fix the error :
 ```
 configure: error: conditional "BUILD_GL" was never defined.
 ```
 full log in the gist.

**Comment by epifanio** [comment]
It seems a configure glitch in the  version of MB-System I was using (5.7.5)  which ignores the supplied configure option. 
Rebuilding the 5.7.8 and master git branch with `--disable0mbtools` builds fine as expected - I guess as it is related to the configure of an old release, this is no longer of interest. I will close the issue.
