### ISSUE TITLE
mb_rt raytrace trajectory

### ISSUE THREAD

**Issue by chrisflesher** [dwcaress/MB-System#1200]
**Is your feature request related to a problem? Please describe.**
When raytracing I would like to get multiple points along a ray vs. time instead of vs. position. Currently we are doing this by calling `mb_rt` multiple times with different `end_time` values but this seems wasteful of CPU resources.

**Describe alternatives you've considered**
There are a couple of different options:
1. Have `mb_rt` return an "end_angle" to allow it to daisy chain multiple small segments together
2. Introduce a `t_plot` argument that would be similar to `x_plot` and `z_plot`. Then you could use this to interpolate x and z vs. time.

**Comment by dwcaress** [comment]
I've modified mb_rt() according to your second suggestion. This change has been merged with the master branch, but is not yet part of a release.

**Comment by chrisflesher** [comment]
Ok, thanks! I'll try it out.

**Comment by chrisflesher** [comment]
This seems to work, thank you!
