### ISSUE TITLE
s7k datafile with 1024 beams

### ISSUE THREAD

**Issue by Phi1983** [dwcaress/MB-System#1234]
Dear mbsystem developers, 
we recently recorded s7k (version 3) data with 1024 beams (Norbit MBES). It was not possible to open these data with the current mbsystem version. A minor change in the file mbs_reson7k3.h solved the problem. I change the value for max. Beams in Line 383 to:

`#define MBSYS_RESON7K_MAX_BEAMS 1024`

After recompiling the code, it works ... so far without problems. 

Best, 
Philipp

**Comment by dwcaress** [comment]
Thanks. This change has been made in my local sandbox, will be included in an upcoming commit.
Is your data from a Norbit WBND multibeam or the newer Windhead? Would you be willing to provide a data sample?
Cheers,
Dave

**Comment by Phi1983** [comment]
Hey Dave,
thanks for your fast reply. The data were recorded with a Norbit iWBMS, but a new Firmware which allows to collect 1024 Beams. 
Can you provide me an Email-address, to send you some data sample. 
Best, 
Philipp
