### ISSUE TITLE
Remove redundant comments

### ISSUE THREAD

**Issue by schwehr** [dwcaress/MB-System#2]
```c
/* return status */
	return (status);
```

Can we remove these?  There are other similar comments, but this is the most glaring one.  It eats up tons of lines without adding the reader.  If you are ok with this o e, I will send a pull request

**Comment by dwcaress** [comment]
Kurt,

Ok, that would be fine.

Thanks,
Dave

> On Sep 10, 2018, at 9:40 AM, Kurt Schwehr <notifications@github.com> wrote:
> 
> /* return status */
> 
> 	
> return (status);
> Can we remove these? There are other similar comments, but this is the most glaring one. It eats up tons of lines without adding the reader. If you are ok with this o e, I will send a pull request
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

----------------------------------------------------
David W. Caress
Principal Engineer
Seafloor Mapping Lab

Monterey Bay Aquarium Research Institute
7700 Sandholdt Road
Moss Landing, CA 95039

caress@mbari.org
http://www.mbari.org/~caress/

Phone: 831-775-1775

**Comment by schwehr** [comment]
Found them with

```sh
find . -name \*.c | xargs grep -v fprintf | grep --color -nH -i --null -e "return status[^;]"
```
