### ISSUE TITLE
Make README.md file and replace old README

### ISSUE THREAD

**Issue by abanbj** [dwcaress/MB-System#456]
I've made a pull request of making a *README.md* to make it in markdown. I think this should replace the original README. Markdown is as good as old school (no offence) README's.

**Comment by dwcaress** [comment]
Thanks, abanbj, the markdown version looks good.
Dave

**Comment by abanbj** [comment]
Much obliged, David. Glad to be contributing.

**Comment by abanbj** [comment]
Closing. We can keep the original README if you want, David. But it's a hassle to keep two files with essentially same contant up to date.
