### ISSUE TITLE
Travis-CI build

### ISSUE THREAD

**Issue by schwehr** [dwcaress/MB-System#8]
I'm working on setting up Travis-CI build of MB-System.  I'm planning on two initial builds: osx and linux.  The biggest thing so far is the need for gmt5.

I'm not sure the best way to approach this and you'll find a bunch of fumbling around here:

https://github.com/schwehr/MB-System/tree/travis-ci

**Comment by dwcaress** [comment]
Kurt,
Ok.
Thanks,
Dave


> On Sep 19, 2018, at 1:37 PM, Kurt Schwehr <notifications@github.com> wrote:
> 
> I'm working on setting up Travis-CI build of MB-System. I'm planning on two initial builds: osx and linux. The biggest thing so far is the need for gmt5.
> 
> I'm not sure the best way to approach this and you'll find a bunch of fumbling around here:
> 
> https://github.com/schwehr/MB-System/tree/travis-ci
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

----------------------------------------------------
David W. Caress
Principal Engineer
Seafloor Mapping Lab

Monterey Bay Aquarium Research Institute
7700 Sandholdt Road
Moss Landing, CA 95039

caress@mbari.org
http://www.mbari.org/~caress/

Phone: 831-775-1775

**Comment by joa-quim** [comment]
Kurt,
I'm building GMT5 in Travis [here ](https://github.com/GenericMappingTools/GMT.jl/blob/master/.travis.yml)for the GMT Julia wrapper. You can probably copy the relevant bits.

**Comment by schwehr** [comment]
Thanks for the suggestion!
