### ISSUE TITLE
Build error: "BUILD_GL" was never defined.

### ISSUE THREAD

**Issue by zepinto** [dwcaress/MB-System#978]
During the configuration process, I get the following error:

> About to create Makefiles...
> checking that generated files are newer than configure... done
> configure: error: conditional "BUILD_GL" was never defined.
> Usually this means the macro was only invoked conditionally.

**Comment by dwcaress** [comment]
Found the logic error in configure.ac, and fixed it. 
Tested on Mac, will test on CentOS before finalizing.
The fix will appear in the next beta release.

**Comment by dwcaress** [comment]
And thanks, Zepinto.
